# Generated by Django 2.2.5 on 2020-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_user_class_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='following',
            field=models.ManyToManyField(related_name='user_user', through='login.User', to='login.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identify',
            field=models.CharField(choices=[('guest', '學生'), ('teacher', '引導師')], default='guest', max_length=123),
        ),
    ]
