# Generated by Django 2.2.5 on 2020-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200906_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_user',
            field=models.ManyToManyField(blank=True, to='login.User'),
        ),
    ]
