# Generated by Django 2.2.5 on 2020-09-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200906_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='following',
        ),
    ]
